# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "linux-pod.fullname" . }}
#   labels:
#     app.kubernetes.io/name: {{ include "linux-pod.name" . }}
#     helm.sh/chart: {{ include "linux-pod.chart" . }}
#     app.kubernetes.io/instance: {{ .Release.Name }}
#     app.kubernetes.io/managed-by: {{ .Release.Service }}
# spec:
#   type: {{ .Values.service.type }}
#   selector:
#     app.kubernetes.io/name: {{ include "linux-pod.name" . }}
#     app.kubernetes.io/instance: {{ .Release.Name }}
#   ports:
#     - name: http
#       protocol: TCP
#       port: {{ .Values.service.port }}
#       targetPort: {{ .Values.service.targetPort }}