apiVersion: v1
kind: ConfigMap
metadata:
  name: indexsearch-consul-configmap
  labels:
    name: indexsearch-consul-configmap
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
data:
  indexsearch-service.properties: |-
{{ .Files.Get "files/indexsearch-service.properties" | indent 4 }}
