---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: recordstore
  labels:
    name: recordstore
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  replicas: {{.Values.replicas}}
  selector:
        matchLabels:
          name: recordstore
  template:
    metadata:
      labels:
        name: recordstore
        cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      
      containers:
      - name: recordstore
        image: {{.Values.repo}}/recordstore-service:{{.Values.version}}{{.Values.tagSufix}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            scheme: HTTP
            port: 8090
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            scheme: HTTP
            port: 8090
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        env:
        - name: CONSUL_HOST
          value: "{{.Values.consul.server}}"
        - name: CONSUL_PORT
          value: "{{.Values.consul.port}}"
        - name: KAFKA_BOOTSTRAP_URL
          value: "{{.Values.kafka.bootstrap}}:{{.Values.kafka.port}}"
        - name: RECORDSTORE_IP
          value: "{{.Values.postgres.ip}}"
        - name: RECORDSTORE_CONNECTION_STRING
          value: "{{.Values.postgres.url}}"
        - name: RECORDSTORE_USERNAME
          value: "{{.Values.postgres.user}}"
        - name: RECORDSTORE_PASSWORD
          value: "{{.Values.postgres.password}}"
        - name: METABASE_CONNECTION_USER
          value: "{{.Values.postgres.user}}"
        - name: METABASE_CONNECTION_PASSWORD
          value: "{{.Values.postgres.password}}"
        - name: METABASE_CONNECTION_URL
          value: "{{.Values.postgres.metabase.url}}"
        - name: DATASETS_USERNAME
          value: "{{.Values.datasets.user}}"
        - name: DATASETS_PASSWORD
          value: "{{.Values.datasets.password}}"  
        - name: ZIPKIN_URL
          value: "{{.Values.zipkin.schema}}://{{.Values.zipkin.ip}}:{{.Values.zipkin.port}}"
        - name: REDIS_HOST
          value: "{{.Values.redis.ip}}"
        - name: REDIS_PORT
          value: "{{.Values.redis.port}}"
        - name: REDIS_SENTINEL_MASTER
          value: "{{.Values.redis.sentinel}}"
        - name: REDIS_SENTINEL_NODES
          value: "{{.Values.redis.nodes}}"  
        - name: DATASET_CREATION_NOTIFICATION_MS
          value: "{{.Values.dataset.creation.notification.ms}}"
        - name: RESTORE_SNAPSHOT_FILE_BUFER
          value: "{{.Values.snapshot.bufferSize}}"  
        - name: DATASET_USERS
          value: "{{.Values.dataset.users}}"  
        - name: SENTRY_DSN
          value: "{{.Values.sentry.dsn}}"
        - name: SENTRY_ENVIRONMENT
          value: "{{.Values.sentry.environment}}"
        - name: SENTRY_RELEASE
          value: "{{.Values.version}}"

        volumeMounts:
        - mountPath: "/reportnet3-data/snapshots"
          name: snapshots-data  
      volumes:
      - name: snapshots-data
        persistentVolumeClaim:
            claimName: reportnet3-data
            
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
