apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-consul-configmap
  labels:
    name: orchestrator-consul-configmap
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
data:
orchestrator.properties: |-
{{ .Files.Get "files/orchestrator.properties" | indent 4 }}
