apiVersion: v1
kind: ConfigMap
metadata:
  name: dataset-consul-configmap
  labels:
    name: dataset-consul-configmap
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
data:
  dataset-service.properties: |-
{{ .Files.Get "files/dataset-service.properties" | indent 4 }}
