# Default values for consul.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
HttpPort: 8500
RpcPort: 8400
SerflanPort: 8301
SerflanUdpPort: 8301
SerfwanPort: 8302
SerfwanUdpPort: 8302
ServerPort: 8300
ConsulDnsPort: 8600
Domain: consul
Component: "consul"
DatacenterName: dc1
Replicas: 3
Image: "hashicorp/consul"
ImageTag: "1.10.0"
ImagePullPolicy: "Always"
Resources: 
 # requests:
 #   cpu: "100m"
 #   memory: "256Mi"
 # limits:
 #   cpu: "500m"
 #   memory: "512Mi"
 requests:
   #cpu: "100m"
   memory: "0.2Gi"
 limits:
   #cpu: "500m"
   memory: "0.2Gi"
priorityClassName: ""
Storage: "20Gi"
DisableHostNodeId: false
# DatacenterName: dc1
joinPeers: []
joinWan: []
Gossip:
  Encrypt: true
  Create: true
# GossipKey: key
StorageClass: nfs-storage
maxUnavailable: 1
# nodeAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#     nodeSelectorTerms:
#     - matchExpressions:
#       - key: cloud.google.com/gke-preemptible
#         operator: NotIn
#         values:
#         - true
affinity: |
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: component
            operator: In
            values:
            - "{{ .Release.Name }}-{{ .Values.Component }}"
ui:
  enabled: true
uiService:
  enabled: true
  type: "NodePort"
  annotations: {}
ConsulConfig: []
#  - type: secret
#    name: consul-defaults
#  - type: configMap
#    name: consul-defaults
uiIngress:
  enabled: false
  annotations: {}
  labels: {}
  hosts: []
  path: /
  tls: []
acl:
  enabled: false
  masterToken: ""
  agentToken: ""
test:
  image: lachlanevenson/k8s-kubectl
  imageTag: v1.4.8-bash
  rbac:
    create: false
    serviceAccountName: ""
nodeSelector: {}
tolerations: []
additionalLabels: {}
podAnnotations: {}
# Lifecycle for StatefulSet
# lifecycle:
#   preStop:
#     exec:
#       command:
#       - sh
#       - -c
#       - "sleep 60"
forceIpv6: false
