apiVersion: v1
kind: ConfigMap
metadata:
  name: document-consul-configmap
  labels:
    name: document-consul-configmap
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
data:
  document-service.properties: |-
{{ .Files.Get "files/document-service.properties" | indent 4 }}
