kind: Service
apiVersion: v1
metadata:
  name: inspire
  labels:
    name: inspire
    namespace: {{.Release.Namespace}}
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  ports:
  - protocol: TCP
    port: 8050
    targetPort: 8050
    nodePort: 0
  selector:
    name: inspire
  type: ClusterIP
  sessionAffinity: None