# nfs-storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.56.105        # Your NFS server IP
  share: /opt/nfs-storage    # NFS export path
  subDir: "${pvc.metadata.namespace}/${pvc.metadata.name}"
  mountPermissions: "0777"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - noresvport