# Default values for reportnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Specific Values for Document

# Environment Variables
consul:
  server: consul.reportnet.svc.cluster.local
  port: 8500

kafka:
  bootstrap: kafka.reportnet.svc.cluster.local
  port: 9092

mongo:
  host: mongo-mongodb
  port: 27017
  hosts: mongo-mongodb-replicaset-0.mongo-mongodb-replicaset.reportnet.svc.cluster.local:27017,mongo-mongodb-replicaset-1.mongo-mongodb-replicaset.reportnet.svc.cluster.local:27017,mongo-mongodb-replicaset-2.mongo-mongodb-replicaset.reportnet.svc.cluster.local:27017/?readPreference=primary&retryWrites=true

redis:
    ip: redis.reportnet.svc.cluster.local
    port: 6379
    sentinel: masterset
    nodes: redis:26379

file:
    path: /reportnet3-data/input

tagSufix: 
replicas: 1
version: v3.4-SANDBOX
repo: eeacms
# Other Variables
 