---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dataset
  labels:
    name: dataset
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  replicas: {{.Values.replicas}}
  selector:
        matchLabels:
          name: dataset
  template:
    metadata:
      labels:
        name: dataset
        cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      
      containers:
      - name: dataset
        image: {{.Values.repo}}/dataset-service:{{.Values.version}}{{.Values.tagSufix}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8030
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8030
          initialDelaySeconds: 80
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8030
          initialDelaySeconds: 65
          periodSeconds: 20
        env:
        - name: CONSUL_HOST
          value: "{{.Values.consul.server}}"
        - name: CONSUL_PORT
          value: "{{.Values.consul.port}}"
        - name: KAFKA_BOOTSTRAP_URL
          value: "{{.Values.kafka.bootstrap}}:{{.Values.kafka.port}}"
        - name: METABASE_CONNECTION_URL
          value: "{{.Values.metabase.url}}"
        - name: METABASE_CONNECTION_USER
          value: "{{.Values.metabase.user}}"
        - name: METABASE_CONNECTION_PASSWORD
          value: "{{.Values.metabase.password}}"
        - name: DATASETS_USERNAME
          value: "{{.Values.datasets.user}}"
        - name: DATASETS_PASSWORD
          value: "{{.Values.datasets.password}}"  
        - name: ZIPKIN_URL
          value: "{{.Values.zipkin.schema}}://{{.Values.zipkin.ip}}:{{.Values.zipkin.port}}"
        - name: REDIS_HOST
          value: "{{.Values.redis.ip}}"
        - name: REDIS_PORT
          value: "{{.Values.redis.port}}"
        - name: MONGO_HOSTS
          value: "{{.Values.mongo.hosts}}"
        - name: "MONGO_DB_HOST"
          value: "{{.Values.mongo.host}}"
        - name: "MONGO_DB_PORT"
          value: "{{.Values.mongo.port}}"
        - name: REDIS_SENTINEL_MASTER
          value: "{{.Values.redis.sentinel}}"
        - name: REDIS_SENTINEL_NODES
          value: "{{.Values.redis.nodes}}"  
        - name: SENTRY_DSN
          value: "{{.Values.sentry.dsn}}"
        - name: SENTRY_ENVIRONMENT
          value: "{{.Values.sentry.environment}}"
        - name: SENTRY_RELEASE
          value: "{{.Values.version}}"
        - name: DATASET_PATH
          value: "{{.Values.file.path}}"                                   
        
        volumeMounts:
        - mountPath: "{{.Values.file.path}}"
          name: load-data  
      volumes:
      - name: load-data
        persistentVolumeClaim:
            claimName: reportnet3-data
                            
        
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
