kind: Service
apiVersion: v1
metadata:
  name: indexsearch
  labels:
    name: indexsearch
    namespace: {{.Release.Namespace}}
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  ports:
  - protocol: TCP
    port: 9030
    targetPort: 9030
    nodePort: 0
  selector:
    name: indexsearch
  type: ClusterIP
  sessionAffinity: None