kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dataflow
  labels:
    name: dataflow
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        name: dataflow
        cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
    spec:
      containers:
      - name: dataflow
        image: {{.Values.repo}}/dataflow-service:{{.Values.version}}{{.Values.tagSufix}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8020
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8020
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8020
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: CONSUL_HOST
          value: "{{.Values.consul.server}}"
        - name: CONSUL_PORT
          value: "{{.Values.consul.port}}"
        - name: KAFKA_BOOTSTRAP_URL
          value: "{{.Values.kafka.bootstrap}}:{{.Values.kafka.port}}"
        - name: METABASE_CONNECTION_URL
          value: "{{.Values.metabase.url}}"
        - name: METABASE_CONNECTION_USER
          value: "{{.Values.metabase.user}}"
        - name: METABASE_CONNECTION_PASSWORD
          value: "{{.Values.metabase.password}}"
        - name: ZIPKIN_URL
          value: "http://{{.Values.zipkin.ip}}:{{.Values.zipkin.port}}"
        - name: REDIS_HOST
          value: "{{.Values.redis.ip}}"
        - name: REDIS_PORT
          value: "{{.Values.redis.port}}"
        - name: REDIS_SENTINEL_MASTER
          value: "{{.Values.redis.sentinel}}"
        - name: REDIS_SENTINEL_NODES
          value: "{{.Values.redis.nodes}}"  
 
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
