{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-ha.postgresql" . }}-metrics
  labels: {{- include "postgresql-ha.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  {{- if .Values.metrics.annotations }}
  annotations: {{- include "postgresql-ha.tplValue" (dict "value" .Values.metrics.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
  selector: {{- include "postgresql-ha.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
