kind: Service
apiVersion: v1
metadata:
  name: frontend
  labels:
    name: frontend
    namespace: {{.Release.Namespace}}
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: {{.Values.frontendPort}}
  selector:
    name: frontend
  type: NodePort
  sessionAffinity: None