apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script-config-map
  labels:
    name: init-script-config-map
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
data:
  Init_Metabase_BD.sql: |-
{{ .Files.Get "files/Init_Metabase_BD.sql" | indent 4 }}
