# Default values for reportnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Specific Values for orchestrator-service

# Environment Variables
consul:
  server: consul
  port: 8500

kafka:
  bootstrap: bootstrap-kafka
  port: 9092

zipkin:
    ip: zipkin-ui
    port: 9411
    schema: https
redis:
    ip: redis
    port: 6379
    sentinel: mymaster
    nodes: redis:26379
file:
    path: /reportnet3-data/input

sentry:
    dsn: https://f1057cea7e954e1a8e11d76bab0a53fd@sentry.eea.europa.eu/46
    environment: dev

orchestrator:
    curl: jdbc:postgresql://rn3-pg-helm-pgpool:5432/orchestrator_db
    user: postgres
    pswd: 
      valueFrom:
        secretKeyRef:
        name: pg-secret
        key: pg-pass
         
axon:
    url: jdbc:postgresql://rn3-pg-helm-pgpool:5432/axon
    user: postgres
    pswd: 
      valueFrom:
        secretKeyRef:
        name: pg-secret
        key: pg-pass

tagSufix: 
replicas: 4
repo: eeacms
version: 1.0.0
# Other Variables
