# Default values for reportnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Specific Values for Validation

# Environment Variables
consul:
  server: consul
  port: 8500

kafka:
  bootstrap: bootstrap-kafka
  port: 9092

metabase:
    url: jdbc:postgresql://rn3-pg-helm-pgpool:5432/metabase
    user: validation
    password: password
datasets:
    user: validation
    password: password
mongo:
  host: mongo-mongodb
  port: 27017
  hosts: mongo-mongodb-replicaset-0.mongo-mongodb-replicaset.reportnet.svc.cluster.local:27017,mongo-mongodb-replicaset-1.mongo-mongodb-replicaset.reportnet.svc.cluster.local:27017,mongo-mongodb-replicaset-2.mongo-mongodb-replicaset.reportnet.svc.cluster.local:27017/?readPreference=primary&retryWrites=true

validation:
    fieldBatchSize: 15000
    recordBatchSize: 15000
    tasks:
        release:
            tax: 1
        initial:
            tax: 1
zipkin:
    ip: zipkin-ui
    port: 9411
redis:
    ip: redis
    port: 6379
    sentinel: mymaster
    nodes: redis:26379
tagSufix: 
replicas: 4
version: 1.0.0
repo: eeacms
# Other Variables
