---
kind: Service
apiVersion: v1
metadata:
  name: collaboration
  labels:
    name: collaboration
    namespace: {{.Release.Namespace}}
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  ports:
  - protocol: TCP
    port: 9060
    targetPort: 9060
    nodePort: 0
  selector:
    name: collaboration
  type: ClusterIP
  sessionAffinity: None