# Default values for reportnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Specific Values for Recordstore

# Environment Variables
consul:
  server: consul
  port: 8500

kafka:
  bootstrap: bootstrap-kafka
  port: 9092

postgres:
    ip: postgres-cluster-beta.eea-test
    url: jdbc:postgresql://rn3-pg-helm:5432/datasets
    metabase: 
        url: jdbc:postgresql://rn3-pg-helm:5432/metabase
    user: testuser
    password: password
zipkin:
    ip: zipkin-ui
    port: 9411
redis:
    ip: redis-master
    port: 6379
    
tagSufix: 
replicas: 1
repo: eeacms
# Other Variables
