apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: reportnet3-data
    labels:
        app: recordstore
        cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{.Values.storageClassName}}