---
# Default values for reportnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Specific Values for UMS
# Environment Variables

consul:
  server: consul.reportnet.svc.cluster.local
  port: 8500

kafka:
  bootstrap: bootstrap-kafka.reportnet.svc.cluster.local
  port: 9092

keycloak:
  - name: user
    valueFrom:
      secretKeyRef:
        name: ums-kc
        key: username
  - name: password
    valueFrom:
      secretKeyRef:
        name: ums-kc
        key: password
    clientId: reportnet
    realm: Reportnet
    host: keycloak-http

redis:
  ip: redis
  port: 6379
  sentinel: masterset
  nodes: redis:26379
file:
  path: /reportnet3-data/input

tagSufix:
replicas: 1
version: v3.4-SANDBOX
repo: eeacms
# Other Variables
