# Default values for reportnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Specific Values for Api Gateway

# Environment Variables
replicas: 5

api-gateway:
  resources:
    limits:
      #cpu: "100m"
      memory: 0.1Gi
    requests:
      #cpu: "100m"
      memory: 0.1Gi


consul:
  server: consul.reportnet.svc.cluster.local
  port: 8500

kafka:
  bootstrap: 	bootstrap-kafka-controller-headless.reportnet.svc.cluster.local
  port: 9092

redis:
    ip: redis
    port: 6379
    sentinel: masterset
    nodes: redis:26379

tagSufix: 
replicas: 1
repo: eeacms
version: v3.4-SANDBOX
# Other Variables
