---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: keycloak
  labels:
    name: keycloak
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: keycloak
        cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
    spec:
      containers:
      - name: keycloak
        image: {{.Values.repo}}/keycloak-eulogin:3.0
#        command: [ "/bin/sh","-c"]
#        args: ["/opt/jboss/keycloak/bin/add-user-keycloak.sh -r admin -u admin -p admin","/opt/jboss/keycloak/bin/standalone.sh"]
        imagePullPolicy: "Always"
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
          failureThreshold: 3
          periodSeconds: 60
