---
kind: Service
apiVersion: v1
metadata:
  name: dataflow
  labels:
    name: dataflow
    namespace: {{.Release.Namespace}}
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  ports:
  - protocol: TCP
    port: 8020
    targetPort: 8020
    nodePort: 0
  selector:
    name: dataflow
  type: ClusterIP
  sessionAffinity: None