# usage: ./eea-deployer install -f /config-staging-nkp.yaml
charts:
##################################### CONSUL ###########################################
  - release_name: consul
    chart_name: consul
    chart_repo: ../consul
    values_file: rn3-staging-nkp-consul.yaml
##################################### CONSUL ###########################################
  - release_name: consul
    chart_name: consul
    chart_repo: ../consul
    values_file: rn3-staging-nkp-consul.yaml
##################################### ARGO CD ###########################################
  # - release_name: argocd
  #   chart_name: argo-cd
  #   chart_repo: https://argoproj.github.io/argo-helm
  #   values_file: values/argo-cd.yaml
  #   version: 6.4.0
  #   namespace: reportnet