apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dump-metabase-dev
  labels:
    component: dump-metabase-dev

spec:
  schedule: {{.Values.schedule }}
  #schedule: "0 7 * * *" 
  #debugging only - every hour 
  #schedule: "0 * * * *" 
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pgdump
            env:
              {{- toYaml .Values.envconfig | nindent 13 }}
            resources:
              {{- toYaml .Values.resources | nindent 13 }}

            volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 13 }}          
            #image: bitnami/postgresql-repmgr:11.7.0-debian-10-r74
            image: {{.Values.runner_image }}
            command: ["/bin/sh"]
            args: ["-c", 'mkdir -p /metabase-backups/pgdump/ && pg_dump  -Fc > /metabase-backups/pgdump/mb-bck_$(date +"%m%d%Y_%H%M")-{{.Values.environment }}.dump  && find /metabase-backups/pgdump -type f -mtime +30 -ls -delete && ls -la /metabase-backups/pgdump && sleep 3600']
            # for debugging only !!!
            #args: ["-c", 'mkdir -p /metabase-backups/pgdump/ && pg_dump  -Fc > /metabase-backups/pgdump/mb-bck_$(date +"%m%d%Y_%H%M")-$environment.dump  && find /metabase-backups/pgdump -type f -mtime +3 -ls -delete && ls -la /metabase-backups/pgdump && sleep 3600']
            #args: ["-c", 'mkdir -p /metabase-backups/pgdump/ && pg_dump  -Fc > /metabase-backups/pgdump/mb-bck_$(date +"%m%d%Y_%H%M")-$environment.dump  && find /metabase-backups/pgdump -type f -mtime +3 -ls -delete && ls -l /metabase-backups/pgdump && cat /metabase-backups/pgdump/mb-bck_$(date +"%m%d%Y_%H%M").dump']
            #restore example command 
            #args: ["-c", 'psql -U postgres  -c "create database metabase1;" && pg_restore -d metabase1 -U postgres /metabase-backups/pgdump/mb-bck_07112024_0640.dump && sleep 3600']
            securityContext:
              runAsUser: 0
              privileged: true




          restartPolicy: Never

          volumes:
          {{- toYaml .Values.volumes | nindent 10 }}

