dry_run: false
create_namespace: false
wait: false
timeout: true # If true, defaults to 20 mins
debug: true
kc: /home/sotav/.kube/dev/config
ns: reportnet
init: true
script: true
charts:
      #####################################################################################
      ####################                                           ######################
      ####################                                           ######################
      ####################          DEMO FOR DEPLOY_TYPE="-"         ######################
      ####################                                           ######################
      ####################                                           ######################
      ####################                                           ######################
      #####################################################################################
      ################################### ARGO-CD ######################################
      - release_name: argocd
        chart_name: argo-cd
        chart_repo: https://argoproj.github.io/argo-helm
        values_file: values/argo-cd.yaml
        version: 6.4.0
        namespace: reportnet
        deploy_type: "-"
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      #####################################################################################
      ####################                                           ######################
      ####################                                           ######################
      ####################             DEVOPS HELPER TOOLS           ######################
      ####################                                           ######################
      ####################                                           ######################
      ####################                                           ######################
      #####################################################################################
      ################################### DEVOPS-HELPER ######################################
      - release_name: devops-helper
        chart_name: devops-helper
        version: v0.0.1
        chart_repo: ../devops-helper
        values_file: rn3-dev-ran2-devops-helper.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"

      #####################################################################################
      ####################                                           ######################
      ####################                                           ######################
      ####################                 STATEFULL                 ######################
      ####################                                           ######################
      ####################                                           ######################
      ####################                                           ######################
      #####################################################################################

      #################################### CONSUL ######################################
      - release_name: consul
        chart_name: consul
        version: v0.0.1
        chart_repo: ../consul
        values_file: rn3-dev-ran2-consul.yaml
        namespace: reportnet
        deploy_type: statefull
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### KAFKA ######################################
      - release_name: kafka
        chart_name: kafka
        version: v0.0.1
        chart_repo: ../kafka
        values_file: rn3-dev-ran2-kafka.yaml
        namespace: reportnet
        deploy_type: statefull
        script_shell: "-"
        init_shell: "-"
        custom_deployment: >-
          export chart_repo=../kafka
          export release_name=kafka
          export chart_name=kafka
          export values_file=rn3-dev-ran2-kafka.yaml
          export NS=reportnet
          export KC=~/.kube/dev/config
          export KRAFT_CLUSTER_ID=dev-ran2-kafka-01
          export INTER_BROKER_PASSWORD=$(grep "INTER_BROKER_PASSWORD" .secrets.prv | cut -d '=' -f2)
          export CONTROLLER_PASSWORD=$(grep "CONTROLLER_PASSWORD" .secrets.prv | cut -d '=' -f2)
          helm --kubeconfig $KC -n $NS upgrade --install $release_name $chart_repo/. -f ../kafka/$values_file --set sasl.interbroker.password=$INTER_BROKER_PASSWORD --set sasl.controller.password=$CONTROLLER_PASSWORD --set kraft.clusterId=$KRAFT_CLUSTER_ID --set resources.requests.memory=3Gi --set resources.limit.memory=3Gi --debug ;


      #################################### KEYCLOAK ######################################
      - release_name: keycloak
        chart_name: keycloak
        version: v0.0.1
        chart_repo: ../keycloak
        values_file: rn3-dev-ran2-keycloak.yaml
        namespace: reportnet
        deploy_type: statefull
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### KEYCLOAK 6-9 ######################################
      # - release_name: keycloak6
      #   chart_name: keycloak6
      #   #version: v0.0.1
      #   chart_repo: ../keycloak-k
      #   values_file: rn3-dev-ran2-keycloak6.yaml
      #   namespace: reportnet
      #   deploy_type: "-"
      #   #script_shell: 
      #   #init_shell:
      #################################### MONGO ######################################
      - release_name: mongo
        chart_name: mongo
        version: v0.0.1
        chart_repo: ../mongodb
        values_file: rn3-dev-ran2-mongo.yaml
        namespace: reportnet
        deploy_type: statefull
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      #################################### REDIS ######################################
      - release_name: redis
        chart_name: redis
        version: v0.0.1
        chart_repo: ../redis
        values_file: rn3-dev-ran2-redis.yaml
        namespace: reportnet
        deploy_type: statefull
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### POSTGRESQL ######################################
      - release_name: rn3-pg-helm
        chart_name: helm
        version: v0.0.1
        chart_repo: ../postgresql
        values_file: rn3-dev-ran2-postgresql.yaml
        namespace: reportnet
        deploy_type: "-" #statefull
        script_shell: >-
          export dbpass=$(grep DBPASS .secrets.prv | cut -d '=' -f2);
          export repmgrpass=$(grep REPMGRPASS .secrets.prv | cut -d '=' -f2);
          export adminpass=$(grep ADMINPASS .secrets.prv | cut -d '=' -f2);
          kubectl --kubeconfig $KC -n $NS exec -i -t -n reportnet rn3-pg-helm-postgresql-0 -c postgresql -- bash -c 'rm -Rf  /tmp/migration';
          kubectl --kubeconfig $KC -n $NS cp ../postgresql/migration rn3-pg-helm-postgresql-0:/tmp/;
          kubectl --kubeconfig $KC -n $NS exec -i -t -n reportnet rn3-pg-helm-postgresql-0 -c postgresql -- bash -c 'ls -la  /tmp/migration';
          chmod a+x ./scripts/migrate.sh;
          ./scripts/migrate.sh;
          chmod a+x ./scripts/pgpool-usr-fix.sh;
          ./scripts/pgpool-usr-fix.sh dev $NS $KC
        init_shell: >-
          kubectl --kubeconfig $KC -n $NS delete secret pg-secret;
          export dbpass=$(grep DBPASS .secrets.prv | cut -d '=' -f2);
          export repmgrpass=$(grep REPMGRPASS .secrets.prv | cut -d '=' -f2);
          export adminpass=$(grep ADMINPASS .secrets.prv | cut -d '=' -f2);
          kubectl --kubeconfig $KC -n $NS create secret generic pg-secret --from-literal admin-password=$adminpass --from-literal pg-pass=$dbpass --from-literal pg-sand-data-pass=postgres --from-literal postgresql-password=$dbpass --from-literal repmgr-password=$repmgrpass;
        custom_deployment: >-
          export chart_repo=../postgresql
          export release_name=helm
          export chart_name=rn3-pg
          export values_file=../postgresql/rn3-dev-ran2-postgresql.yaml
          export NS=reportnet
          export dbpass=$(grep DBPASS .secrets.prv | cut -d '=' -f2);
          export repmgrpass=$(grep REPMGRPASS .secrets.prv | cut -d '=' -f2);
          export adminpass=$(grep ADMINPASS .secrets.prv | cut -d '=' -f2);
          helm --kubeconfig $KC -n $NS upgrade --install rn3-pg-$release_name $chart_repo/. -f $values_file --set fullnameOverride=rn3-pg-helm,metrics.enabled=true --debug;
      #################################### CITUS ######################################
      - release_name: citus
        chart_name: citus
        version: v0.0.1
        chart_repo: ../citus
        values_file: rn3-dev-ran2-citus.yaml
        namespace: reportnet
        deploy_type: statefull
        script_shell: "-"
        init_shell: >-
          export dbpass=$(grep DBPASS .secrets.prv | cut -d '=' -f2);
          export pass=$(grep DBPASS .secrets.prv | cut -d '=' -f2);
          kubectl --kubeconfig $KC -n $NS delete secret citus-secrets;
          kubectl --kubeconfig $KC -n $NS create secret generic citus-secrets --from-literal password=$pass --from-literal userpass=$dbpass ;
        custom_deployment: "-"
          #helm --kubeconfig $KC -n $NS upgrade --install citus . -f rn3-staging-nkp-citus.yaml --set fullnameOverride=citus,metrics.enabled=true --debug

      #####################################################################################
      ####################                                           ######################
      ####################                                           ######################
      ####################              INGRESSES                    ######################
      ####################                                           ######################
      ####################                                           ######################
      ####################                                           ######################
      #####################################################################################


      ################################### NGINX  ######################################
      # - release_name: nginx
      #   chart_name: nginx
      #   version: v0.0.1
      #   chart_repo: ../traefik
      #   values_file: rn3-dev-ran2-nginx-svc-api.yaml
      #   namespace: reportnet
      #   deploy_type: "-"
      #   script_shell: "-"
      #   init_shell: "-"
      #   custom_deployment: "-"
      ################################### TRAEFIK ######################################
      - release_name: traefik
        chart_name: traefik
        version: v0.0.1
        chart_repo: ../traefik
        values_file: rn3-dev-ran2-traefik_values.yaml
        namespace: reportnet
        deploy_type: "-"
        script_shell: >-
          kubectl --kubeconfig $KC apply -f  ../traefik/rn3-dev-ran2-traefik-svc-api.yaml
        init_shell: "-"
        custom_deployment: "-"

      #####################################################################################
      ####################                                           ######################
      ####################                                           ######################
      ####################              DEPLOYMENTS                  ######################
      ####################                                           ######################
      ####################                                           ######################
      ####################                                           ######################
      #####################################################################################

      #################################### KAFKA-UI ######################################
      - release_name: kafka-ui
        chart_name: kafka-ui
        debug: true
        version: v0.0.1
        chart_repo: ../kafka-ui
        values_file: rn3-dev-ran2-kafka-ui.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### RECORDSTORE #####################################
      - release_name: recordstore
        chart_name: helm
        version: v0.0.1
        chart_repo: ../reportnet-recordstore
        values_file: rn3-dev-ran2-recordstore.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: >-
          kubectl --kubeconfig $KC apply -f  ../reportnet-recordstore/rn3-dev-ran2-data-pvc-nfs.yaml
        custom_deployment: "-"
      ################################### APIGATEWAY ######################################
      - release_name: api-gateway
        chart_name: reportnet-api-gateway
        version: v0.0.1
        chart_repo: ../reportnet-apigateway
        values_file: rn3-dev-ran2-api-gateway.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### COLLABORATION ######################################
      - release_name: collaboration
        chart_name: reportnet-collaboration
        version: v0.0.1
        chart_repo: ../reportnet-collaboration
        values_file: rn3-dev-ran2-collaboration.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### COMMUNICATION ######################################
      - release_name: communication
        chart_name: reportnet-communication
        version: v0.0.1
        chart_repo: ../reportnet-communication
        values_file: rn3-dev-ran2-communication.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### DATAFLOW ######################################
      - release_name: dataflow
        chart_name: reportnet-dataflow
        version: v0.0.1
        chart_repo: ../reportnet-dataflow
        values_file: rn3-dev-ran2-dataflow.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### DATASET ######################################
      - release_name: dataset
        chart_name: reportnet-dataset
        version: v0.0.1
        chart_repo: ../reportnet-dataset
        values_file: rn3-dev-ran2-dataset.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### DOCUMENT ######################################
      - release_name: document
        chart_name: reportnet-document
        version: v0.0.1
        chart_repo: ../reportnet-document
        values_file: rn3-dev-ran2-document.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### FRONTEND ######################################
      - release_name: frontend
        chart_name: reportnet-frontend
        version: v0.0.1
        chart_repo: ../reportnet-frontend
        values_file: rn3-dev-ran2-frontend.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### ORCHESTRATOR ######################################
      - release_name: orchestrator
        chart_name: reportnet-orchestrator
        version: v0.0.1
        chart_repo: ../reportnet-orchestrator
        values_file: rn3-dev-ran2-orchestrator.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### ROD ######################################
      - release_name: rod
        chart_name: reportnet-rod
        version: v0.0.1
        chart_repo: ../reportnet-rod
        values_file: rn3-dev-ran2-rod.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### UMS ######################################
      - release_name: ums
        chart_name: reportnet-ums
        version: v0.0.1
        chart_repo: ../reportnet-ums
        values_file: rn3-dev-ran2-ums.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### VALIDATION ######################################
      - release_name: validation
        chart_name: reportnet-validation
        version: v0.0.1
        chart_repo: ../reportnet-validation
        values_file: rn3-dev-ran2-validation.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"
      ################################### MAINTENANCE ######################################
      - release_name: maintenance
        chart_name: reportnet-maintenance
        version: v0.0.1
        chart_repo: ../reportnet-maintenance
        values_file: rn3-dev-ran2-maintenance.yaml
        namespace: reportnet
        deploy_type: deployment
        script_shell: "-"
        init_shell: "-"
        custom_deployment: "-"


















