#!/bin/bash

# Author: Tavoulas Sotiris @ eea.europa.eu
# Version: 1.0.1
# Date published: 29/05/2026
# Date updated: 29/05/2026
# Description: This is a small bash utility which can help to install and uninstall multiple helm charts in one go.
# Github URL: 
# usage: 
#     ./eea-deployer install -f ./config-staging-nkp.yaml

# Enable debug mode
# set -x





show_menu(){
    normal=`echo "\033[m"`
    menu=`echo "\033[36m"` #Blue
    number=`echo "\033[33m"` #yellow
    bgred=`echo "\033[41m"`
    fgred=`echo "\033[31m"`
    printf "\n${menu}*********************************************${normal}\n"
    printf "${menu}**${number} 1)${menu} Show what will get deployed ${normal}\n"
    printf "${menu}**${number} 2)${menu} Show Help - Config ${normal}\n"
    printf "${menu}**${number} 3)${menu} *** DEPLOY ALL *** ${normal}\n"
    printf "${menu}**${number} 4)${menu} to be -- Deploy only Statefull ${normal}\n"
    printf "${menu}**${number} 5)${menu} to be -- Deploy only Deployments ${normal}\n"
    printf "${menu}**${number} 6)${menu} to be -- Deploy only an app ${normal}\n"
    printf "${menu}*********************************************${normal}\n"
    printf "Please enter a menu option and enter or ${fgred}x to exit. ${normal}"
    read opt
}

option_picked(){
    msgcolor=`echo "\033[01;31m"` # bold red
    normal=`echo "\033[00;00m"` # normal white
    message=${@:-"${normal}Error: No message passed"}
    printf "${msgcolor}${message}${normal}\n"
}



# Function to show help on how to use this utility? and what all options are available
# It also contains a sample config.yaml file which is a must for this utility to function properly.
show_help() {
  echo "Usage: $0 [OPTIONS] [ARGUMENTS - Optional]"
  echo "--------------------------"
  echo "Options:"
  echo "--------------------------"
  echo "  install      Install multiple helm charts in one go.
               Just need to have config.yaml file with what all charts needs to be installed.
               For more information around config.yaml, sample file is a part of base folder."
  echo "  uninstall    Uninstall multiple helm charts in one go, this command too will consume the
               same config.yaml."
  echo "  help         Display help."
  echo ""
  echo "--------------------------"
  echo "Arguments:"
  echo "--------------------------"
  echo "  -f | --file  Helps you to mention explicit/specific config.yaml. If not provided it 
               will consider the default one which is placed in the base folder."
  echo ""
  echo "Sample config.yaml:"
  echo "--------------------------
dry_run: false
create_namespace: false
wait: false
timeout: true # If true, defaults to 20 mins
charts:
##################################### CONSUL ###########################################
  - release_name: consul
    chart_name: consul
    chart_repo: ../consul
    values_file: rn3-staging-nkp-consul.yaml
##################################### KAFKA UI ###########################################
  - release_name: kafka-ui
    chart_name: kafka-ui
    chart_repo: ../kafka-ui
    values_file: rn3-staging-nkp-kafka-ui.yaml

Note: 
--------------------------
- Charts is an array, it can contain as many releases as you want.
- It support both oci:// and https:// registries.
- All the key value pairs under charts are mandatory except version and namespace.
  - If not provided it will consider latest chart and default namespace respectively.
- You can mention explicit/specific config.yaml as well using -f | --file flag. 
  - If not provided it will consider the default one which is placed in the base folder.
  - If config.yaml is placed in /tmp directory, it might not work correctly. Ref: 
- Initial messages are printed using cowsay (It is not necessary though if required, get this installed using apt/yum/brew/dpkg based on your distribution).

Example:
--------------------------
$ ./eea-deployer install -f ./config-staging-nkp.yaml "

  #exit 0
}
























eea_master() {
# install yq if it does not exists !
if ! which yq > /dev/null; then
   echo -e "YQ python not found! Installing ........ \c"
    sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    sudo chmod a+x /usr/local/bin/yq
    yq --version
    printf "status: success\ndata:\n  - name: Sotav\n    age: 48\n  - name: EEA\n    age: 26" > test.yaml
    yq e '.' test.yaml
fi
# The FUN PART !!! 
# Reset
Color_Off='\033[0m'       # Text Reset
# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White
# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White
# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White
# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White
# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White
# Function to show initial message which is created using cowsay
# It is not necessary though if required, get this installed using apt/yum/brew/dpkg based on your distribution
eea-deployer() {
  which cowsay > /dev/null
  if [[ $? == "0" ]]; then
    MESSAGE=$1
    echo -e "\e[5m\e[1;31m$MESSAGE\e[0m" | cowsay -f tux.cow -n
  else
    MESSAGE=$1
    log_message "INFO" "$MESSAGE"
  fi
}
cowthinker() {
  which cowthink > /dev/null
  if [[ $? == "0" ]]; then
    MESSAGE=$1
    echo -e "\e[5m\e[1;31m$MESSAGE\e[0m" |cowthink -n
  else
    MESSAGE=$1
    log_message "INFO" "$MESSAGE"
  fi
}
# get and export the kubeconfig file to set as a variable for the script to run 
export WD=$(pwd)
export KC=$(yq e '.kc' $3)
export NS=$(yq e '.ns' $3)
export NAMESPACE=$(yq e '.ns' $3)
cowthinker "Default values are: $KC $NS $WD"

# Set the path of log and archive logs, these logs are basically eea-deployer logs
LOG_DEST="logs"
mkdir -p $LOG_DEST/archive
LOG_FILE="$LOG_DEST/eea-deployer.log"
ARCHIVE_LOG_FILE="eea-deployer_$(date +'%Y%m%d_%H%M%S').tar.gz"

# Compress older log file and remove old log file if it already exists
if [ -f "$LOG_FILE" ]; then
  tar -czf $ARCHIVE_LOG_FILE "$LOG_FILE"
  mv $ARCHIVE_LOG_FILE $LOG_DEST/archive
  rm "$LOG_FILE"
fi


# Function to standardize log messages with LOG_LEVEL and LOG_TIME
# Plus to make sure they are printed on the STDOUT as well as in the log_file
log_message() {
  LOG_TIME=$(date +"%Y-%m-%d %H:%M:%S")
  LOG_LEVEL=$1
  MESSAGE=$2

  echo "[$LOG_TIME] [$LOG_LEVEL] $MESSAGE"
  echo "[$LOG_TIME] [$LOG_LEVEL] $MESSAGE" >> "$LOG_FILE"
}
# Function to check pod health and to make sure pods of a given release are in running state 
# This script will terminate if the pods are not running for more than 20 minutes, which is something that should ideally not happen.
check_pod_status() {
  RELEASE_NAME=$1
  NAMESPACE=$(yq e '.ns' $3)
  KC=$(yq e '.kc' $3)
  log_message "INFO" "Checking for pods status with ( RELEASE_NAME: $RELEASE_NAME, NAMESPACE: $NAMESPACE,  KUBECONFIG: $KC )"
  START_TIME=$(date +%s)
  while true; do
    CURRENT_TIME=$(date +%s)
    ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
    if [[ $ELAPSED_TIME -gt 1200 ]]; then
      log_message "INFO" "##############################"
      log_message "ERROR" "Pods for release $RELEASE_NAME are not in Running state for more than 20 minutes. Exiting"
      log_message "ERROR" "Error code: 2"
      log_message "INFO" "##############################"s
      exit 2
    fi
    TOTAL_PODS=$(kubectl --kubeconfig $KC --namespace $NAMESPACE get pods  |grep $RELEASE_NAME  | wc -l)
    if [[ $TOTAL_PODS == "0" ]]; then
      log_message "INFO" "##############################"
      log_message "ERROR" "There are no pods for $RELEASE_NAME"
      log_message "ERROR" "Error code: 3"
      log_message "INFO" "##############################"
      #exit 3
    else
      POD_STATUS=$(kubectl --kubeconfig $KC -n $NAMESPACE get pods  | grep $RELEASE_NAME  | awk -F " " '{print $2}' | grep -vi running | wc -l)
      if [[ $POD_STATUS != "0" ]]; then
        log_message "INFO" "All Pods for release $RELEASE_NAME are in Running state"
        log_message "INFO" "Amount of running Pods for release $RELEASE_NAME are $POD_STATUS"
        POD_AMOUNT=$(kubectl --kubeconfig $KC get pods -n $NAMESPACE | grep $RELEASE_NAME | awk -F " " '{print $2}' | grep -vi running | wc -l)
        log_message "INFO" "Running Pods are : $POD_AMOUNT"
        log_message "INFO" "##############################"
        log_message "INFO" "##############################"

        break
      else
        log_message "WARN" "Pods for release $RELEASE_NAME are not yet in Running state, checking again in 5 seconds"
        log_message "INFO" "Amount of running Pods for release $RELEASE_NAME are $POD_STATUS"
        POD_AMOUNT=$(kubectl --kubeconfig $KC get pods -n $NAMESPACE | grep $RELEASE_NAME | awk -F " " '{print $2}' | grep -vi running | wc -l)
        log_message "INFO" "Running Pods are : $POD_AMOUNT"
        log_message "INFO" "##############################"
        log_message "INFO" "##############################"
        sleep 5
      fi            
      log_message "WARN" "Pods for release $RELEASE_NAME are not yet in Running state, checking again in 5 seconds"
      sleep 5
    fi
  done
}
# Function to log what all generic values we have in our config.yaml file
generic_values() {
  log_message "INFO" "Generic/common values based on $CONFIG_FILE_NAME file"
  
  DRY_RUN=$(yq e '.dry_run' $CONFIG_FILE_NAME)
  CREATE_NAMESPACE=$(yq e '.create_namespace' $CONFIG_FILE_NAME)
  WAIT=$(yq e '.wait' $CONFIG_FILE_NAME)
  TIMEOUT=$(yq e '.timeout' $CONFIG_FILE_NAME)
  KUBECONFIG=$($KC)

  log_message "INFO" "Dry Run: $DRY_RUN"
  log_message "INFO" "Create Namespace: $CREATE_NAMESPACE"
  log_message "INFO" "Wait: $WAIT"
  log_message "INFO" "Timeout: $TIMEOUT"
  log_message "INFO" "KubeConfig: $KC"
  log_message "INFO" "****************************"  
}
# Funtion to log what all chart specific values we have in our config.yaml file
generic_chart_values() {
  log_message "INFO" "Chart specific values based on $CONFIG_FILE_NAME file"
  log_message "INFO" "Release Name: $RELEASE_NAME"
  log_message "INFO" "Chart Name: $CHART_NAME"
  log_message "INFO" "Debug: $DEBUG"
  log_message "INFO" "Version: $VERSION"
  log_message "INFO" "Chart Repo: $CHART_REPO"
  log_message "INFO" "Values File: $VALUES_FILE"
  log_message "INFO" "Namespace: $NAMESPACE"
  log_message "INFO" "Deploy type: $DEPLOY_TYPE"
  log_message "INFO" "Script_shell: $SCRIPT_SHELL"
  log_message "INFO" "Init_shell: $INIT_SHELL"
  log_message "INFO" "Custom_deployment: $CUSTOM_DEPLOYMENT"
}
# Function for the main logic and what all option we have in this utility
perform_action() {
  ACTION=$1
  #RELEASE_NAME=$2
  #CHART_NAME=$4
  #VERSION=$5
  #CHART_REPO=$6
  #VALUES_FILE=$3
  #NAMESPACE=$7
  #DEPLOY_TYPE=$8
  #SCRIPT_SHELL=$9
  #INIT_SHELL=${10}
  #CUSTOM_DEPLOYMENT=${12}
  #DRY_RUN=${12}
  #CREATE_NAMESPACE=${13}
  #WAIT=${13}
  #TIMEOUT=${14}
  FULL_REPO=$CHART_REPO/$CHART_NAME
  REPO_TYPE="oci"

    printf "${BYellow} Performing according actions.......  ${Color_Off}\n"
  #cowthinker "Default values are: Kubeconfig: $KC Dry Run: $DRY_RUN , Create Namespace: $CREATE_NAMESPACE, Wait: $WAIT, Timeout: $TIMEOUT, Working Directory: $WD"

  if [[ $CHART_REPO == "https://"* ]]; then
    REPO_NAME=$(echo $CHART_REPO | awk -F/ '{print $3}')
    helm repo add $REPO_NAME $CHART_REPO > /dev/null
    FULL_REPO=$REPO_NAME/$CHART_NAME
    REPO_TYPE="https"
  fi

  if [[ $NAMESPACE == null ]]; then
    NAMESPACE="reportnet"
  fi

  if [ "$ACTION" == "install" ]; then

    if [ "$DEPLOY_TYPE" == "-" ]; then
      log_message "INFO" "Deployment type is '-' deployment will not be executed "
      printf "${Red} Deployment type is '-' deployment will not be executed  ${Color_Off} \n"
    fi



    ##################################################################
    # run before the deployment
    if [ "$DEPLOY_TYPE" != "-" ] && [ "$INIT_SHELL" != "-" ]; then
      log_message "INFO" "Custom SHELL INIT  detected"
      printf "${Red} Custom SHELL INIT  detected ${Color_Off} \n"
      log_message "INFO" "Executing SHELL INIT command: $INIT_SHELL"
      #log_message "INFO" "****************************"
      #eval $INIT_SHELL
      eval $INIT_SHELL >> $LOG_FILE 2>&1
    fi
    ##################################################################

    #log_message "INFO" "Deployment type is *** $DEPLOY_TYPE *** "



    if [ "$DEPLOY_TYPE" != "-" ] && [ "$CUSTOM_DEPLOYMENT" != "-" ] ; then
      log_message "INFO" "Custom deployment detected"
      printf "${Red} Custom deployment detected  ${Color_Off} \n"
      log_message "INFO" "Executing custom deployment command: $CUSTOM_DEPLOYMENT"
      #log_message "INFO" "****************************"
      eval $CUSTOM_DEPLOYMENT >> $LOG_FILE 2>&1
    else

      # if [ "$CUSTOM_DEPLOYMENT" == "-" ]; then
      #   log_message "INFO" "NO custom deployment detected"
      #   else
      #   log_message "INFO" "Custom deployment detected"
      # fi
      

      if [ "$DEPLOY_TYPE" == "statefull" ] && [ "$CUSTOM_DEPLOYMENT" == "-" ] ; then
          log_message "INFO" "Deployment type is *** $DEPLOY_TYPE ***  execution will only upgrade "
          HELM_COMMAND="helm --kubeconfig $KC -n "$NAMESPACE" upgrade "$RELEASE_NAME" "$CHART_REPO" -f "$CHART_REPO/$VALUES_FILE""
          #HELM_COMMAND="echo hello from a statefull deployment "
        else
        if [ "$DEPLOY_TYPE" == "deployment" ] && [ "$CUSTOM_DEPLOYMENT" == "-" ] ; then
          log_message "INFO" "Deployment type is  *** $DEPLOY_TYPE ***  execution will proceed "
          log_message "INFO" "Installing $CHART_NAME with release name $RELEASE_NAME from $CHART_REPO with version $VERSION using values file: $VALUES_FILE in $NAMESPACE namespace"
          HELM_COMMAND="helm --kubeconfig $KC -n "$NAMESPACE" upgrade --install "$RELEASE_NAME" "$CHART_REPO" -f "$CHART_REPO/$VALUES_FILE""
        fi
      fi


      if [ "$DRY_RUN" == "true" ]; then
        HELM_COMMAND+=" --dry-run=client"
      fi
    
      if [ "$CREATE_NAMESPACE" == "true" ]; then
        HELM_COMMAND+=" --create-namespace"
      fi
    
      if [ "$WAIT" == "true" ]; then
        HELM_COMMAND+=" --wait"
      fi
    
      if [ "$TIMEOUT" == "true" ]; then
        HELM_COMMAND+=" --timeout=20m"
      fi

      if [ "$VERSION" != "-" ]; then
        HELM_COMMAND+=" --version $VERSION"
      fi
      
      if [ "$DEBUG" == "true" ]; then
        HELM_COMMAND+=" --debug"
      fi
      log_message "INFO" "Executing command: $HELM_COMMAND"
      log_message "INFO" "****************************"
      eval "$HELM_COMMAND" >> "$LOG_FILE" 2>&1
    fi

    # run after the deployment 
    if [ "$DEPLOY_TYPE" != "-" ] && [ "$SCRIPT_SHELL" != "-" ]; then
      log_message "INFO" "Custom SHELL SCRIPT  detected"
      printf "${Red} Custom SHELL SCRIPT  detected ${Color_Off} \n"
      log_message "INFO" "Executing SHELL SCRIPT command: $SCRIPT_SHELL"
      #log_message "INFO" "****************************"
      #eval $SCRIPT_SHELL
      eval $SCRIPT_SHELL >> $LOG_FILE 2>&1
    fi


    ##################################################################

  elif [ "$ACTION" == "uninstall" ]; then
    log_message "INFO" "Uninstalling $CHART_NAME with release name '$RELEASE_NAME' from $NAMESPACE namespace"
    helm --kubeconfig $KC uninstall "$RELEASE_NAME" -n "$NAMESPACE" >> "$LOG_FILE" 2>&1

  else
    eea-deployer "Uh-oh! something is wrong"  
    log_message "INFO" "Usage: $0 [OPTIONS] [ARGUMENTS - Optional]"
    log_message "ERROR" "Invalid action, please see help using './eea-deployer help'"
    log_message "ERROR" "Error code: 4"
    exit 4
  fi


  # Check the status of last executed command
  if [ $? -eq 0 ]; then
    #log_message "INFO" "$ACTION with release name '$RELEASE_NAME' completed successfully in $NAMESPACE namespace"
    log_message "INFO" "All Actions have been completed successfully"
    log_message "INFO" "****************************"
  else
    log_message "ERROR" "Failed to $ACTION $CHART_NAME with release name '$RELEASE_NAME' from/in $NAMESPACE namespace"
    log_message "ERROR" "Check $LOG_FILE for details."
    log_message "INFO" "****************************"
    log_message "ERROR" "Error code: 5"
    #exit 5
  fi
}
# Default config file
CONFIG_FILE_NAME=$3
# Define ACTION i.e. the option which this utility is capable of
ACTION=$1
# Move past the first argument
shift
# Parse command line arguments for the explicit config file path
while [[ "$#" -gt 0 ]]; do
    if [[ "$1" == "-f" || "$1" == "--file" ]]; then
        CONFIG_FILE_NAME="$2"
        echo $CONFIG_FILE_NAME
        # Move past the flag and its value
        shift 2
    else
        log_message "ERROR" "Unknown or unsupported flag: $1"
        log_message "ERROR" "Error code: 7"
        exit 7
    fi
done

# Check if the file exists
if [ ! -f "$CONFIG_FILE_NAME" ]; then
    log_message "ERROR" "File '$CONFIG_FILE_NAME' does not exist"
    log_message "ERROR" "Error code: 8"
    exit 8
fi



###########################################################################################
# Based on the action install, uninstall, etc perform it and provide indented results and logs
if [ "$ACTION" == "install" ]; then
  eea-deployer "Starting deployments of charts !"
  log_message "INFO" "Using file: $CONFIG_FILE_NAME"
  generic_values
  while IFS=$'\t' read -r RELEASE_NAME CHART_NAME VERSION CHART_REPO VALUES_FILE NAMESPACE DEPLOY_TYPE SCRIPT_SHELL INIT_SHELL CUSTOM_DEPLOYMENT; do
    generic_chart_values
    perform_action "$ACTION" "$RELEASE_NAME" "$CHART_NAME" "$CHART_REPO" "$VALUES_FILE" "$VERSION" "$NAMESPACE"  "$DEPLOY_TYPE" "$SCRIPT_SHELL" "$INIT_SHELL" "$CUSTOM_DEPLOYMENT"
    if [ "$DRY_RUN" == "true" ]; then
      log_message "INFO" "Skipping $perform_action due to DRY_RUN=true for release $RELEASE_NAME"
    else
      echo -e "${Green}-------------------------------------------------------------${Color_Off}"
      # or 
      #echo -e "${Green}Waiting for 2 seconds to check the pods ${Color_Off}"
      #sleep 2s
      #check_pod_status "$RELEASE_NAME" "$NAMESPACE" "$CONFIG_FILE_NAME"      
    fi
    #sleep 2s
  done < <(yq e '.charts[] | [.release_name, .chart_name, .version, .chart_repo, .values_file, .namespace, .deploy_type, .script_shell, .init_shell, .custom_deployment] | @tsv' $CONFIG_FILE_NAME)

###########################################################################################
elif [ "$ACTION" == "uninstall" ]; then
  eea-deployer "eea-deployer, Uninstall charts!"
  generic_values
  while IFS=$'\t' read -r RELEASE_NAME CHART_NAME CHART_REPO VALUES_FILE VERSION NAMESPACE; do
    generic_chart_values
    perform_action "$ACTION" "$RELEASE_NAME" "$CHART_NAME" "$CHART_REPO" "$VALUES_FILE" "$VERSION" "$NAMESPACE" "$DRY_RUN" "$CREATE_NAMESPACE" "$WAIT" "$TIMEOUT"
    
    sleep 2s
  done < <(yq e '.charts[] | [.release_name, .chart_name, .chart_repo, .values_file, .version, .namespace] | @tsv' $CONFIG_FILE_NAME)
###########################################################################################

elif [ "$ACTION" == "help" ]; then
  eea-deployer "eea-deployer, Show help!"
  show_help

elif [ "$ACTION" == "preinstall" ]; then
  printf "Config file is : ${Green}$CONFIG_FILE_NAME ${Color_Off} \n"
  generic_values
  while IFS=$'\t' read -r RELEASE_NAME CHART_NAME VERSION CHART_REPO VALUES_FILE NAMESPACE DEPLOY_TYPE SCRIPT_SHELL INIT_SHELL CUSTOM_DEPLOYMENT; do
    printf "######################################################\n"

    if [ "$DEPLOY_TYPE" != "-" ]; then
      printf "Application: ${Green}$RELEASE_NAME ${Color_Off}\n"
      printf "###########\n"
      printf "ACTION: ${Red} $ACTION ${Color_Off}\n"
      printf "RELEASE_NAME: ${Red}$RELEASE_NAME ${Color_Off}\n"
      printf "CHART_NAME: ${Red}$CHART_NAME ${Color_Off}\n" 
      printf "CHART_REPO: ${Red}$CHART_REPO ${Color_Off}\n" 
      printf "VALUES_FILE: ${Red}$VALUES_FILE ${Color_Off}\n" 
      printf "VERSION: ${Red}$VERSION ${Color_Off}\n"
      printf "NAMESPACE: ${Red}$NAMESPACE ${Color_Off}\n"
      printf "DEPLOY_TYPE: ${Red}$DEPLOY_TYPE ${Color_Off}\n"
      printf "SCRIPT_SHELL: ${Red}$SCRIPT_SHELL ${Color_Off}\n"
      printf "INIT_SHELL: ${Red}$INIT_SHELL ${Color_Off}\n"
      printf "CUSTOM_DEPLOYMENT: ${Red}$CUSTOM_DEPLOYMENT ${Color_Off}\n"
      printf "DRY_RUN: ${Red}$DRY_RUN ${Color_Off}\n" 
      printf "CREATE_NAMESPACE: ${Red}$CREATE_NAMESPACE ${Color_Off}\n"
      printf "WAIT: ${Red}$WAIT ${Color_Off}\n"
      printf "TIMEOUT: ${Red}$TIMEOUT ${Color_Off}\n"
    else
      printf "Application: ${Green}$RELEASE_NAME ${Color_Off} will ${Red} * NOT *${Color_Off} get deployed \n the ${Green}DEPLOY_TYPE${Color_Off} is set to ${Red}'-'${Color_Off} \n"
      
      printf "###########\n"

    fi

  done < <(yq e '.charts[] | [.release_name, .chart_name, .version, .chart_repo, .values_file, .namespace, .deploy_type, .script_shell, .init_shell, .custom_deployment] | @tsv' $CONFIG_FILE_NAME)

else
  eea-deployer "Uh-oh! something is wrong"  
  log_message "ERROR" "Invalid action, please see help using 'eea-deployer help'"
  log_message "ERROR" "Error code: 9"
  exit 9
fi

log_message "INFO" "All actions completed successfully"
}



clear
show_menu
while [ $opt != '' ]
    do
    if [ $opt = '' ]; then
      exit;
    else
      case $opt in
        1) clear;
            option_picked "Option selected (1) = Show what will get deployed ";
            eea_master preinstall $2 $3 ;
            show_menu;
        ;;
        2) clear;
            option_picked "Option selected (2) = Show Help - Config";
            show_help;
            cat $3
            show_menu;
        ;;
        3) clear;
            option_picked "Option selected (3) = DEPLOY ALL ";
            #printf "sudo mount /dev/sdh1 /mnt/DropBox/; #The 3 terabyte";
            printf "$1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15}";
            eea_master $1 $2 $3 $4 ;
            show_menu;
        ;;
        4) clear;
            option_picked "Option 4 Picked";
            printf "Option 4 Picked";
            show_menu;
        ;;
        5) clear;
            option_picked "Option 5 Picked";
            printf "Option 5 Picked";
            show_menu;
        ;;
        x)exit;
        ;;
        \n)exit;
        ;;
        *)clear;
            option_picked "Pick an option from the menu";
            show_menu;
        ;;
      esac
    fi
done
