apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mb-bck-0
  namespace: reportnet
  labels:
    app: pv-mb-bck-0
spec:
  storageClassName: reportnet
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nolock
  nfs:
    server: 10.2.200.1
    path: /rn3prod/pv23
  #hostPath:
  #  path: "/metabase-backups"
