apiVersion: v1
kind: ConfigMap
metadata:
  name: recordstore-consul-configmap
  labels:
    name: recordstore-consul-configmap
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
data:
  recordstore-service.properties: |-
{{ .Files.Get "files/recordstore-service.properties" | indent 4 }}
