{{- if (include "postgresql-ha.pgpoolCreateSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-ha.pgpool" . }}
  labels: {{- include "postgresql-ha.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
type: Opaque
data:
  admin-password: {{ (include "postgresql-ha.pgpoolAdminPassword" .) | b64enc | quote }}
{{- end -}}
