# Default values for reportnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Specific Values for Communication

# Environment Variables
consul:
  server: consul
  port: 8500

kafka:
  bootstrap: bootstrap-kafka
  port: 9092

mongo:
  host: mongo-mongodb
  port: 27017
  hosts: mongo-mongodb-replicaset-0.mongo-mongodb-replicaset.reportnet.svc.cluster.local:27017,mongo-mongodb-replicaset-1.mongo-mongodb-replicaset.reportnet.svc.cluster.local:27017,mongo-mongodb-replicaset-2.mongo-mongodb-replicaset.reportnet.svc.cluster.local:27017/?readPreference=primary&retryWrites=true

zipkin:
    ip: zipkin-ui
    port: 9411
    schema: https
redis:
    ip: redis
    port: 6379
    sentinel: mymaster
    nodes: redis:26379

sentry:
    dsn: https://f1057cea7e954e1a8e11d76bab0a53fd@sentry.eea.europa.eu/46
    environment: test

axon:
    url: jdbc:postgresql://rn3-pg-helm-pgpool:5432/axon
    user: postgres
    pswd: 
      valueFrom:
        secretKeyRef:
          name: pg-secret
          key: pg-pass
        
tagSufix: 
replicas: 1
repo: eeacms
version: 1.0.0
# Other Variables
