apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reportnet3-data
  namespace: reportnet
  labels:
    app: reportnet3-data-claim
spec:
  storageClassName: nutanix-file-static
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi