kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Values.pvc.name}}
spec:
  storageClassName: {{.Values.storageClassName}}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.pvc.storage}}
