apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.Values.container.name.replica}}"
  labels:
    name: "{{.Values.container.name.replica}}"
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "{{.Values.container.name.replica}}"
  template:
    metadata:
      labels:
        name: "{{.Values.container.name.replica}}"
      name: "{{.Values.container.name.replica}}"
    spec:
      containers:
      - env:
        - name: PGHOST
          value: /tmp
        - name: PG_PRIMARY_HOST
          value: "{{.Values.container.name.primary}}"
        - name: PG_PRIMARY_USER
          value: primaryuser
        - name: PG_MODE
          value: replica
        - name: PG_PRIMARY_PORT
          value: "{{.Values.container.port}}"
        - name: PG_PRIMARY_PASSWORD
          value: "{{.Values.credentials.primary}}"
        - name: PG_USER
          value: testuser
        - name: PG_PASSWORD
          value: "{{.Values.credentials.user}}"
        - name: PG_DATABASE
          value: userdb
        - name: PG_ROOT_PASSWORD
          value: "{{.Values.credentials.root}}"
        image: "{{.Values.image.repository}}/{{.Values.image.container}}:{{.Values.image.tag}}"
        imagePullPolicy: IfNotPresent
        name: "{{.Values.container.name.replica}}"
        ports:
        - containerPort: {{.Values.container.port}}
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /pgdata
          name: pgdata
        - mountPath: /backup
          name: backup
          readOnly: true
        - mountPath: /pguser
          name: pguser-volume
        - mountPath: /pgprimary
          name: pgprimary-volume
        - mountPath: /pgroot
          name: pgroot-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: pgdata
      - emptyDir: {}
        name: backup
      - name: pguser-volume
        secret:
         secretName: pguser-secret
      - name: pgprimary-volume
        secret:
         secretName: pgprimary-secret
      - name: pgroot-volume
        secret:
         secretName: pgroot-secret
