---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: orchestrator
  labels:
    name: orchestrator
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  replicas: {{.Values.replicas}}
  selector:
        matchLabels:
          name: orchestrator
  template:
    metadata:
      labels:
        name: orchestrator
        cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
      annotations:
        prometheus.io/scrape: "true"
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst

      containers:
      - name: orchestrator
        image: {{.Values.repo}}/orchestrator-service:{{.Values.version}}{{.Values.tagSufix}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            scheme: HTTP
            port: 8091
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            scheme: HTTP
            port: 8091
          initialDelaySeconds: 35
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        env:
        - name: CONSUL_HOST
          value: "{{.Values.consul.server}}"
        - name: CONSUL_PORT
          value: "{{.Values.consul.port}}"
        - name: KAFKA_BOOTSTRAP_URL
          value: "{{.Values.kafka.bootstrap}}:{{.Values.kafka.port}}"
        - name: MONGO_DB_HOST
          value: "{{.Values.mongo.host}}"
        - name: MONGO_DB_PORT
          value: "{{.Values.mongo.port}}"
        - name: METABASE_CONNECTION_URL
          value: "{{.Values.metabase.url}}"
        - name: METABASE_CONNECTION_USER
          value: "{{.Values.metabase.user}}"
        - name: METABASE_CONNECTION_PASSWORD
          value: "{{.Values.metabase.password}}"  
        - name: DATASETS_USERNAME
          value: "{{.Values.datasets.user}}"
        - name: DATASETS_PASSWORD
          value: "{{.Values.datasets.password}}"  
        - name: ZIPKIN_URL
          value: "{{.Values.zipkin.schema}}://{{.Values.zipkin.ip}}:{{.Values.zipkin.port}}"
        - name: REDIS_HOST
          value: "{{.Values.redis.ip}}"
        - name: REDIS_PORT
          value: "{{.Values.redis.port}}"
        - name: MONGO_HOSTS
          value: "{{.Values.mongo.hosts}}"
        - name: "MONGO_DB_HOST"
          value: "{{.Values.mongo.host}}"
        - name: "MONGO_DB_PORT"
          value: "{{.Values.mongo.port}}"  
        - name: REDIS_SENTINEL_MASTER
          value: "{{.Values.redis.sentinel}}"
        - name: REDIS_SENTINEL_NODES
          value: "{{.Values.redis.nodes}}"  
        - name: orchestrator_FIELD_BATCH_SIZE
          value: "{{.Values.orchestrator.fieldBatchSize}}"  
        - name: orchestrator_RECORD_BATCH_SIZE
          value: "{{.Values.orchestrator.recordBatchSize}}"
        - name: orchestrator_TASKS_RELEASE_TAX
          value: "{{.Values.orchestrator.tasks.release.tax}}"
        - name: orchestrator_TASKS_INITIAL_TAX
          value: "{{.Values.orchestrator.tasks.initial.tax}}"
        - name: SENTRY_DSN
          value: "{{.Values.sentry.dsn}}"
        - name: SENTRY_ENVIRONMENT
          value: "{{.Values.sentry.environment}}"
        - name: SENTRY_RELEASE
          value: "{{.Values.version}}"
        - name: orchestrator_EXPORT_FILES_PATH
          value: "{{.Values.file.path}}"  
                            
        volumeMounts:
        - mountPath: "{{.Values.file.path}}"
          name: load-data  
      volumes:
      - name: load-data
        persistentVolumeClaim:
            claimName: reportnet3-data


  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
