# Default values for reportnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Specific Values for Communication

# Environment Variables
consul:
  server: consul
  port: 8500

kafka:
  bootstrap: bootstrap-kafka.reportnet.svc.cluster.local
  port: 9092

zipkin:
    ip: zipkin-ui
    port: 9411
redis:
    ip: redis
    port: 6379
    sentinel: mymaster
    nodes: redis:26379
    
tagSufix: 
replicas: 1
repo: eeacms
version: 1.0.0
# Other Variables
