---
kind: Service
apiVersion: v1
metadata:
  name: api-gateway
  labels:
    name: api-gateway
    namespace: {{.Release.Namespace}}
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
    nodePort: 0
  selector:
    name: api-gateway
  type: ClusterIP
  sessionAffinity: None