kind: Service
apiVersion: v1
metadata:
  name: rod
  labels:
    name: rod
    namespace: {{.Release.Namespace}}
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  ports:
  - protocol: TCP
    port: 9050
    targetPort: 9050
    nodePort: 0
  selector:
    name: rod
  type: ClusterIP
  sessionAffinity: None