kind: Service
apiVersion: v1
metadata:
  name: orchestrator-service
  labels:
    name: orchestrator-service
    namespace: {{.Release.Namespace}}
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  ports:
  - protocol: TCP
    port: 8091
    targetPort: 8091
    
  selector:
    name: orchestrator-service
  type: ClusterIP
  sessionAffinity: None