name: primary-replica
container:
  port: 5432
  name:
    primary: primary
    replica: replica
credentials:
  primary: password
  root: password
  user: password

serviceType: ClusterIP
image:
  repository: crunchydata
  container: crunchy-postgres-gis
  tag: centos7-10.8-2.3.2
pvc:
  storage: 954Mi
  name: primary-pvc
  storageClassName: rook-ceph-block
resources:
  cpu: 200m
  memory: 512Mi
