apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-ha.postgresql" . }}
  labels: {{- include "postgresql-ha.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector: {{- include "postgresql-ha.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
