kind: Service
apiVersion: v1
metadata:
  name: document
  labels:
    name: document
    namespace: {{.Release.Namespace}}
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  ports:
  - protocol: TCP
    port: 9040
    targetPort: 9040
    nodePort: 32240
  selector:
    name: document
  type: NodePort
  sessionAffinity: None