{{- if .Values.ldap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-ha.ldap" . }}
  labels: {{- include "postgresql-ha.labels" . | nindent 4 }}
type: Opaque
data:
  bind-password: {{ (include "postgresql-ha.ldapPassword" .) | b64enc | quote }}
{{- end -}}
