apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2022-04-12T09:42:42Z"
  generation: 24
  labels:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: postgres-cluster-helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-2.2.2
  name: rn3-pg-helm-postgresql
  namespace: reportnet
  resourceVersion: "190733775"
  selfLink: /apis/apps/v1/namespaces/reportnet/statefulsets/rn3-pg-helm-postgresql
  uid: e6181a0f-ba44-11ec-9135-021d34e052a4
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: postgresql
      app.kubernetes.io/instance: postgres-cluster-helm
      app.kubernetes.io/name: postgresql-ha
  serviceName: rn3-pg-helm-postgresql-headless
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-09-11T09:57:45Z"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: postgresql
        app.kubernetes.io/instance: postgres-cluster-helm
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: postgresql-ha
        helm.sh/chart: postgresql-ha-2.2.2
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo The app is running! && sleep 3600
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: POSTGRESQL_VOLUME_DIR
          value: /bitnami/postgresql
        - name: PGDATA
          value: /bitnami/postgresql/data
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: rn3-pg-helm-postgresql
        - name: POSTGRES_DB
          value: postgres
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: REPMGR_UPGRADE_EXTENSION
          value: "no"
        - name: REPMGR_PGHBA_TRUST_ALL
          value: "no"
        - name: REPMGR_MOUNTED_CONF_DIR
          value: /bitnami/repmgr/conf
        - name: REPMGR_PARTNER_NODES
          value: rn3-pg-helm-postgresql-0.rn3-pg-helm-postgresql-headless.reportnet.svc.cluster.local,rn3-pg-helm-postgresql-1.rn3-pg-helm-postgresql-headless.reportnet.svc.cluster.local,rn3-pg-helm-postgresql-2.rn3-pg-helm-postgresql-headless.reportnet.svc.cluster.local,
        - name: REPMGR_PRIMARY_HOST
          value: rn3-pg-helm-postgresql-0.rn3-pg-helm-postgresql-headless.reportnet.svc.cluster.local
        - name: REPMGR_NODE_NAME
          value: $(MY_POD_NAME)
        - name: REPMGR_NODE_NETWORK_NAME
          value: $(MY_POD_NAME).rn3-pg-helm-postgresql-headless.reportnet.svc.cluster.local
        - name: REPMGR_LOG_LEVEL
          value: NOTICE
        - name: REPMGR_CONNECT_TIMEOUT
          value: "5"
        - name: REPMGR_RECONNECT_ATTEMPTS
          value: "3"
        - name: REPMGR_RECONNECT_INTERVAL
          value: "5"
        - name: REPMGR_USERNAME
          value: repmgr
        - name: REPMGR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: repmgr-password
              name: rn3-pg-helm-postgresql
        - name: REPMGR_DATABASE
          value: repmgr
        image: docker.io/bitnami/postgresql-repmgr:11.7.0-debian-10-r74
        imagePullPolicy: IfNotPresent
        name: postgresql
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - PGPASSWORD=$POSTGRES_PASSWORD psql -w -U "postgres" -d "postgres"  -h
              127.0.0.1 -c "SELECT 1"
          failureThreshold: 200
          initialDelaySeconds: 5
          periodSeconds: 700
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/
          name: custom-init-scripts
        - mountPath: /bitnami/postgresql
          name: data
      - env:
        - name: DATA_SOURCE_URI
          value: 127.0.0.1:5432/postgres?sslmode=disable
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: rn3-pg-helm-postgresql
        - name: DATA_SOURCE_USER
          value: postgres
        image: docker.io/bitnami/postgres-exporter:0.8.0-debian-10-r71
        imagePullPolicy: IfNotPresent
        name: metrics
        ports:
        - containerPort: 9187
          name: metrics
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 200
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          defaultMode: 420
          name: rn3-pg-helm-postgresql-initdb-scripts
        name: custom-init-scripts
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 20Gi
      storageClassName: database
    status:
      phase: Pending
status:
  collisionCount: 0
  currentRevision: rn3-pg-helm-postgresql-6f85c95b8
  observedGeneration: 24
  replicas: 1
  updateRevision: rn3-pg-helm-postgresql-79c8c554bb
  updatedReplicas: 1
