apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rn3-pg-helm-postgresql-0
  namespace: reportnet
  labels:
    app: data-rn3-pg-helm-postgresql-0
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rn3-pg-helm-postgresql-1
  namespace: reportnet
  labels:
    app: data-rn3-pg-helm-postgresql-1
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rn3-pg-helm-postgresql-2
  namespace: reportnet
  labels:
    app: data-rn3-pg-helm-postgresql-2
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi