apiVersion: v1
kind: Pod
metadata:
  name: application-e2e
spec:
  containers:
    - name: test-e2e-container
      image: k8s-swi001:5000/altia-e2e-test-framework:1.2
      command: [ "/bin/sh" ]
      args: [ "-c", "git clone https://{{.Values.git.username}}:{{.Values.git.password}}@stash-oami.altia.es/scm/rn3/altia_e2e_test_framework.git master && cd master && npm install --save-dev && sed -i -e 's/\\(\"default\": \"\\).*/\\1{{.Values.reportnet.server}}\"/' cypress.json && npm run cypress:report && read" ]
  restartPolicy: Never