kind: Service
apiVersion: v1
metadata:
  name: orchestrator
  labels:
    name: orchestrator
    namespace: {{.Release.Namespace}}
    cleanup: "{{.Release.Namespace}}-{{.Chart.Name}}-services"
spec:
  ports:
  - protocol: TCP
    port: 8015
    targetPort: 8015
    
  selector:
    name: orchestrator
  type: ClusterIP
  sessionAffinity: None