{{- if (include "postgresql-ha.postgresqlCreateSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-ha.postgresql" . }}
  labels: {{- include "postgresql-ha.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  postgresql-password: {{ (include "postgresql-ha.postgresqlPassword" .) | b64enc | quote }}
  repmgr-password: {{ (include "postgresql-ha.postgresqlRepmgrPassword" .) | b64enc | quote }}
{{- end -}}
